import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/AuthContext";
import { useQuery } from "@tanstack/react-query";
import { getAllOrganizations, getProfile } from "./api/services";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const useProfile = () =>
  useQuery({
    queryKey: ["profile"],
    queryFn: getProfile,
  });

export const useOrganization = () =>
  useQuery({
    queryKey: ["organization"],
    queryFn: getAllOrganizations,
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <AuthProvider>
          <body className={inter.className}>
            <main>{children}</main>
            <Toaster />
          </body>
        </AuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
