import {
  ArrowRight,
  BookCheck,
  CoinsIcon,
  Container,
  CreditCardIcon,
  DatabaseBackupIcon,
  GitPullRequestCreate,
  HandCoinsIcon,
  HeartHandshakeIcon,
  LayoutDashboardIcon,
  LoaderCircle,
  LogOutIcon,
  ReceiptText,
  RouteIcon,
  TruckIcon,
  User,
  UserPenIcon,
  UserRound,
  UserRoundCheck,
  UserRoundCogIcon,
  UsersRound,
  WalletMinimal,
} from "lucide-react";

export const Icons = {
  dashboard: LayoutDashboardIcon,
  profile: UserPenIcon,
  transactions: CreditCardIcon,
  beneficiary: HeartHandshakeIcon,
  account: UserRoundCogIcon,
  shippers: TruckIcon,
  vendors: UserRoundCheck,
  routes: RouteIcon,
  history: DatabaseBackupIcon,
  investments: HandCoinsIcon,
  withdrawals: CoinsIcon,
  logout: LogOutIcon,
  arrowRight: ArrowRight,
  order: GitPullRequestCreate,
  example: BookCheck,
  finance: WalletMinimal,
  spinner: LoaderCircle,
  load: Container,
  client: UsersRound,
  investor: UserRound,
  shipper: User,
  mobilization: CreditCardIcon,
  invoice: ReceiptText,
};
